# Generated by Django 3.1 on 2020-09-19 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('headline', models.TextField(blank=True, max_length=200)),
                ('country', models.TextField(blank=True, max_length=200)),
                ('city', models.TextField(blank=True, max_length=200)),
                ('employed', models.CharField(choices=[['yes', 'yes'], ['no', 'no']], max_length=10)),
                ('employer', models.TextField(blank=True, max_length=200)),
                ('education_level', models.CharField(choices=[['masters', 'masters'], ['bachelors', 'bachelors']], max_length=10)),
                ('major', models.TextField(blank=True, max_length=200)),
                ('school', models.TextField(blank=True, max_length=200)),
                ('fav_coding_lang', models.TextField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
