# Generated by Django 3.1 on 2020-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_coding_lang',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
