# Generated by Django 3.1 on 2020-10-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201022_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_tech_stack',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
