# Generated by Django 3.1 on 2020-09-04 20:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='snippet',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
