# Generated by Django 3.1 on 2020-09-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0002_auto_20200904_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='explanation',
            field=models.TextField(default='NO EXPLANATION', max_length=500),
        ),
    ]
