# Generated by Django 3.1 on 2020-09-14 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csnip', '0004_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='snippets_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
