# Generated by Django 3.1 on 2020-09-14 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csnip', '0005_snippet_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='author',
            field=models.ForeignKey(default='NONAME', on_delete=django.db.models.deletion.CASCADE, related_name='snippets_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
