# Generated by Django 3.1 on 2020-09-14 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csnip', '0006_auto_20200914_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='author',
            field=models.CharField(max_length=500, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets_created', to=settings.AUTH_USER_MODEL)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
