# Generated by Django 3.1 on 2020-09-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0007_auto_20200914_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
