# Generated by Django 3.1 on 2020-09-18 22:03

from django.db import migrations
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('csnip', '0009_auto_20200917_1900'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='snippet',
            managers=[
                ('publishedd', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
