# Generated by Django 3.1 on 2020-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0010_auto_20200915_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
