# Generated by Django 3.1 on 2020-09-19 19:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0010_auto_20200918_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
