# Generated by Django 3.1 on 2020-09-22 05:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0011_auto_20200919_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
