# Generated by Django 3.1 on 2020-09-27 21:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csnip', '0013_auto_20200922_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='explanation_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_vector','explanation_vector'], name='csnip_snipp_title_v_5f21e6_gin'),
        ),

        migrations.RunSQL(
            '''
            DROP TRIGGER IF EXISTS text_vector_update ON public.csnip_snippet;
            CREATE TRIGGER text_vector_update
            BEFORE INSERT OR UPDATE
            ON public.csnip_snippet
            FOR EACH ROW
            EXECUTE PROCEDURE tsvector_update_trigger(explanation_vector, 'pg_catalog.english', explanation);
            UPDATE public.csnip_snippet set ID=ID;
            '''
        ),

        migrations.RunSQL(
            '''
            DROP TRIGGER IF EXISTS title_vector_update ON public.csnip_snippet;
            CREATE TRIGGER title_vector_update
            BEFORE INSERT OR UPDATE
            ON public.csnip_snippet
            FOR EACH ROW
            EXECUTE PROCEDURE tsvector_update_trigger(title_vector, 'pg_catalog.english', title);
            UPDATE public.csnip_snippet set ID=ID;
            '''
        ),


    ]
